# Generated by Django 4.2 on 2023-04-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
    ]
