# Generated by Django 4.2 on 2023-05-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='milage',
            new_name='mileage',
        ),
    ]
