# Generated by Django 4.2 on 2023-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_milage_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='county',
            field=models.CharField(choices=[('Bong', 'Bong'), ('Bomi', 'Bomi'), ('Gbarpolu', 'Gbarpolu'), ('Grand Bassa', 'Grand Bassa'), ('Grand Cape Mount', 'Grand Cape Mount'), ('Grand Gedeh', 'Grand Gedeh'), ('Grand Kru', 'Grand Kru'), ('Lofa', 'Lofa'), ('Margibi', 'Margibi'), ('Maryland', 'Maryland'), ('Montserrado', 'Montserrado'), ('Nimba', 'Nimba'), ('Rivercess', 'Rivercess'), ('River Gee', 'River Gee'), ('Sinoe', 'Sinoe')], max_length=100),
        ),
    ]
